server:
    port: ${PORT:5000}
spring:
    data:
        rest:
            base-path: /api
    jpa:
        properties:
            hibernate:
                default_schema: beecoolbo
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
        url: ${JDBC_DATABASE_URL:}