server:
    port: ${PORT:5000}
spring:
    datasource:
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
        url: ${JDBC_DATABASE_URL:}
    profiles:
        active: production